name: Deploy Theme
on:
  push:
    branches:
      - release/hadb.me
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - name: Build theme
        env:
          NODE_ENV: production
        run: npx gulp build
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
